version: '3.3'

services:

  app:
    container_name: backend_container
    build: 
      context: ./API
      dockerfile: ./API
    restart: always
    volumes: 
      - .:/home/developer
    ports: 
      - 8000:8000
    expose: 
      - "8000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - "27017"
    ports:
      - 27017:27017
    restart: unless-stopped
    # volumes: 
    #   - FAPP_userdata:/home/FAPP_userdata

# volumes: 
#   FAPP_userdata:
#     external: true