version: '3.3'

services:
  mongodb:
      image: mongo
      container_name: mongo_db
      environment:
        - PUID=1000
        - PGID=1000
      ports:
        - 27017:27017
      restart: unless-stopped